config/routes.rb
Rails.application.routes.draw do
  root to: 'recommendations#index'

  resources :recommendations, only: [:index, :show]
  resources :people, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  validates_presence_of :title
  validates_uniqueness_of :number

  has_many :recommendations
  has_and_belongs_to_many :people
end

app/models/person.rb
class Person < ApplicationRecord
  validates_presence_of :first_name, :last_name

  has_many :recommendations
  has_and_belongs_to_many :episodes, order: 'release_date DESC'

  scope :ordered, -> { joins(:episodes)
                         .order(Episode.arel_table[:release_date].desc)
                         .order(Person.arel_table[:last_name]).uniq }
  scope :current_hosts, -> { where(is_current_host: true).where(is_former_host: false) }
  scope :former_hosts, -> { where(is_current_host: false).where(is_former_host: true) }
  scope :guest_hosts, -> { where(is_current_host: false).where(is_former_host: false) }


  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  validates_presence_of :name

  belongs_to :person
  belongs_to :episode

  default_scope { includes(:episode).includes(:person).order("episodes.release_date desc").order("people.first_name") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @hosts = Person.current_hosts.ordered
    @former_hosts = Person.former_hosts.ordered
    @guests = Person.guest_hosts.ordered
  end

  def show
    @person = Person.find(params[:id])
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  def index
    @recommendations = Recommendation.all
  end

  def show
    @recommendation = Recommendation.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WsyRecommends</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <div class="top-bar">
      <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
          <li>
            <a href="<%= root_path %>">
              <%= image_tag('logo.png', size: '64') %>
              Who Shot Ya Recommends
            </a>
          </li>
          <li>
            <a class="left-menu-link" href="<%= people_path %>">
              Recs By Host
            </a>
          </li>
        </ul>
      </div>
    </div>
  </header>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/people/index.html.erb
<h3>Recommendations by Person</h3>
<h4>Current Hosts</h4>
<ul class="current-hosts">
  <% @hosts.each do |person| %>
    <li>
      <a href="<%= person_path(person) %>">
        <%= person.full_name %>
      </a>
    </li>
  <% end %>
</ul>
<h4>Former Hosts</h4>
<ul class="former-hosts">
  <% @former_hosts.each do |person| %>
    <li>
      <a href="<%= person_path(person) %>">
        <%= person.full_name %>
      </a>
    </li>
  <% end %>
</ul>
<h4>Guests</h4>
<ul class="guest-hosts">
  <% @guests.each do |person| %>
    <li>
      <a href="<%= person_path(person) %>">
        <%= person.full_name %>
      </a>
    </li>
  <% end %>
</ul>

app/views/people/show.html.erb
<h3><%= @person.full_name %></h3>
<ul>
  <% @person.recommendations.each do |rec| %>
    <li><%= rec.name %> - <%= rec.episode.release_date.strftime('%m/%-d/%Y') %></li>
  <% end %>
</ul>

app/views/recommendations/index.html.erb
<h3>Recommendations</h3>
<p>All the movies recommended by the hosts and guests of the Who Shot Ya podcast, chronologically by episode.</p>
<ul>
  <% @recommendations.each do |r| %>
    <li class="recommendation-title"><%= link_to(r.name, recommendation_path(r)) %> - <%= r.person.full_name %></li>
  <% end %>
</ul>

<p>A fan site and labor of love. Who Shot Ya and Maximum Fun are not responsible for the content of this site.</p>

app/views/recommendations/show.html.erb
<h2><%= @recommendation.name %></h2>
<p><%= @recommendation.person.full_name %></p>
<p>Episode <%= @recommendation.episode.number %></p>